baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "reveal-hugo"

[params.reveal_hugo]
highlight_theme = "github"
load_default_plugins = true

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true